db:
  reference: hg19.fa
  reference_dict: hg19.dict
  gene_entrez: hg19_gene_symbol_to_entrezid.txt
  transcript:
    refgene: hg19_refgene_transcript
  filter_based:
    gnomad_exome: hg19_gnomad_exome
param:
  splicing_distance = 2
